### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by lanlan990802** [Time-MoE/Time-MoE#10]
Could you please advise me on how to resolve this issue after importing the Transformer library from Hugging Face?
ValueError: TimeSeriesTransformerForPrediction does not support Flash Attention 2.0 yet. Please request to add support where the model is hosted, on its model hub page: https://huggingface.co/Maple728/TimeMoE-50M/discussions/new or in the Transformers GitHub repo: https://github.com/huggingface/transformers/issues/new

**Comment by Maple728** [comment]
Sure, here’s a refined version of your message:

---

I apologize, but I'm having trouble understanding your comment.

It seems the issue might be related to Flash Attention 2.0. You could try loading the model with the `eager` attention implementation instead of FA. Here’s how you can do it:

```python
model = xx.from_pretrained(model_path, *args, attn_implementation='eager')
```

In Time-MoE, we've made some modifications to adapt it to HuggingFace's `AutoModelForCausalLM` class. You can find the implementation details at: [TimeMoE-50M Implementation](https://huggingface.co/Maple728/TimeMoE-50M/blob/main/modeling_time_moe.py). We hope this resource is helpful for you.
