### ISSUE TITLE
preprocessing time series

### ISSUE THREAD

**Issue by Sample-design-alt** [Time-MoE/Time-MoE#22]
Thanks for your great works! 
But I have some problem with preprocess time series. I don't know how to convert the each dataset splited into multiple binary files and how to deal with missing values.

Could you please share the code or relevant github repo to preprocess time series?

**Comment by Maple728** [comment]
Thank you for your interest in our work.

The script to convert data into binary files will be released next week. In the meantime, if your memory can accommodate your dataset, you can follow the instructions in the [Prepare dataset](https://github.com/Time-MoE/Time-MoE?tab=readme-ov-file#preparing-your-dataset) section to process your dataset. Once processed, you can use it to fine-tune your model.

If you have any questions, please feel free to contact us.

**Comment by iganggang** [comment]
Dear author
I see the **Prepare dataset** section in README, but I still do not find the code to convert .csv file to .json to input the model. Could you tell me where it is?
thank you very much.

**Comment by Maple728** [comment]
Due to the arbitrary format of users' raw datasets, providing a uniform conversion code is challenging.

In the [Prepare Dataset](https://github.com/Time-MoE/Time-MoE?tab=readme-ov-file#preparing-your-dataset) section of the README, we describe the data format required by the fine-tuning script. This format is straightforward, and you can easily convert your raw dataset to the format used by Time-MoE with minimal code.

Please feel free to contact us if you have any questions.
