### ISSUE TITLE
Analyzing the Impact of Auxiliary Loss on MSE in ETTh1: Key Observations from Table 11

### ISSUE THREAD

**Issue by iganggang** [Time-MoE/Time-MoE#25]
![屏幕截图 2024-11-27 092630](https://github.com/user-attachments/assets/7c334c4d-0b19-4d4d-a48a-35f9a06723dc)

I have read Table 11 many times but still don't understand. Without moe and auxiliary loss, the MSE of ETTh1 is 0.37, and without auxiliary loss, the MSE of ETTh1 is 0.368. It seems that the auxiliary loss has the greatest influence. I am confused. Could you help me point it?

**Comment by Maple728** [comment]
Thank you for your interest in our work.

When the auxiliary loss is removed, the MoE layer tends to collapse into a smaller feed-forward network (FFN) due to an imbalance in expert load during training. As a result, the model becomes more akin to a dense model with a smaller FFN, leading to poorer performance compared to a standard dense model.

This phenomenon is explained in Section 4.3:

> "We also removed the auxiliary loss from the objective function, retaining only the auto-regressive loss (w/o auxiliary loss) while still using the MoE architecture. This adjustment caused the expert layers to collapse into a smaller FFN during training, as the activation score of the most effective expert became disproportionately stronger without the load balance loss."

Please feel free to contact us if you have any questions.

**Comment by iganggang** [comment]
Thank you very much.
