### ISSUE TITLE
Time stamps for the sequences

### ISSUE THREAD

**Issue by aldro61** [Time-MoE/Time-MoE#28]
Hi,

Thanks for sharing your great work!

I followed the instructions in the README to load sequences from Time-300B. It looks like `ds[seq_idx]` returns the sequence's numerical values but not the timestamps. Can you please indicate how to get the timestamps for each point?

**Comment by Maple728** [comment]
Thank you for your interest in our work!

Unfortunately, the Time-300B does not store timestamp information. The `meta.json` file contains essential details about the sequences, such as their length and offset in the binary files. Including timestamps (like start and end times, and granularity) would double the size of the `meta.json` file, which isn't ideal for devices with limited memory. This is because all `meta.json` files are loaded into memory during training. As such, we decided to exclude timestamp information from the Time-300B.

If you need the timestamps for each sequence, you can find them in the original datasets. The sources are listed in [our paper](https://arxiv.org/pdf/2409.16040).

Please feel free to contact us, if you have any questions.
